import { useState } from 'react';

type V2 = [number, number];
const W = 420; const O = 210; const S = 48;
const toSvg = ([x, y]: V2): V2 => [O + x * S, O - y * S];
function tip(lambda: number) { if (lambda === 1) return 'λ = 1: вектор не меняется. Это как матрица-единица для этого направления.'; if (lambda === 0) return 'λ = 0: вектор исчезает в нуле. Это направление — ядро матрицы.'; if (lambda < 0) return `λ = ${lambda.toFixed(1)}: вектор перевернулся и ${Math.abs(lambda) > 1 ? `удлинился в ${Math.abs(lambda).toFixed(1)} раза` : 'сжался'}.`; return `λ = ${lambda.toFixed(1)}: вектор ${lambda > 1 ? `растягивается в ${lambda.toFixed(1)} раза` : 'сжимается'}, но остаётся на той же прямой.`; }
function Arrow({ v, color, dashed }: { v: V2; color: string; dashed?: boolean }) { const [x, y] = toSvg(v); return <g><line x1={O} y1={O} x2={x} y2={y} stroke={color} strokeWidth="5" strokeLinecap="round" strokeDasharray={dashed ? '8 6' : undefined}/><circle cx={x} cy={y} r="7" fill={color}/></g>; }
export default function EigenStretchVectorLab() { const [lambda, setLambda] = useState(2); const eigen: V2 = [2.2, 1.1]; const image: V2 = [eigen[0] * lambda, eigen[1] * lambda]; const other: V2 = [-1.1, 2.3];
  return <div><h4 className="text-xl font-extrabold text-slate-900">Лаборатория 1: «Растяжение вектора»</h4><p className="mt-2 text-sm text-slate-700">Формула Ax=λx означает: собственный вектор не покидает свою прямую, меняется только масштаб.</p><div className="mt-4 flex flex-wrap gap-2">{[1,0,-1,2,0.5].map(v=><button key={v} onClick={()=>setLambda(v)} className="rounded-xl border border-indigo-200 bg-indigo-50 px-3 py-2 text-sm font-bold text-indigo-800">λ={v}</button>)}</div><div className="mt-5 grid gap-5 lg:grid-cols-[440px_1fr]"><svg viewBox={`0 0 ${W} ${W}`} className="rounded-3xl border border-slate-200 bg-white">{Array.from({length:9},(_,i)=>i-4).map(g=><g key={g}><line x1={O+g*S} x2={O+g*S} y1="0" y2={W} stroke={g?'#e2e8f0':'#64748b'}/><line y1={O+g*S} y2={O+g*S} x1="0" x2={W} stroke={g?'#e2e8f0':'#64748b'}/></g>)}<line x1={toSvg([-5,-2.5])[0]} y1={toSvg([-5,-2.5])[1]} x2={toSvg([5,2.5])[0]} y2={toSvg([5,2.5])[1]} stroke="#ef4444" opacity="0.25" strokeWidth="10"/><Arrow v={other} color="#F97316" dashed/><Arrow v={eigen} color="#EF4444"/><Arrow v={image} color="#3B82F6"/><text x="18" y="28" fill="#ef4444" fontWeight="800">x — собственный вектор</text><text x="18" y="50" fill="#3b82f6" fontWeight="800">λx — результат A</text><text x="18" y="72" fill="#f97316" fontWeight="800">обычный вектор: не обязан сохранять прямую</text></svg><div className="space-y-4"><div className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex justify-between font-bold"><span>Собственное значение λ</span><span>{lambda.toFixed(1)}</span></div><input type="range" min={-3} max={3} step={0.1} value={lambda} onChange={e=>setLambda(Number(e.target.value))} className="w-full accent-indigo-600"/><p className="mt-3 text-sm text-slate-700">{tip(lambda)}</p></div><div className="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><b>💡 Ключевое наблюдение:</b> собственный вектор никогда не покидает свою прямую. Меняется только длина и, возможно, направление на противоположное.</div></div></div></div>;
}
