export type TocItem = { id: string; label: string };

// Каждый id здесь соответствует <section id="..."> в соответствующем rich theory.
// При добавлении новой секции в theory-rich — обновите этот список.
export const TOPIC_TOC: Record<string, TocItem[]> = {
  'Операции с матрицами': [
    { id: 'basics',    label: 'Определение и структура матрицы' },
    { id: 'add',       label: 'Сложение и вычитание' },
    { id: 'scalar',    label: 'Умножение на скаляр' },
    { id: 'transpose', label: 'Транспонирование' },
    { id: 'multiply',  label: 'Матричное умножение' },
    { id: 'trace',     label: 'След матрицы' },
    { id: 'norm',      label: 'Норма матрицы' },
    { id: 'inverse',   label: 'Обратная матрица' },
    { id: 'ds',        label: 'Матрицы в Data Science' },
    { id: 'check',     label: 'Проверь себя' },
  ],
  'Ранг и базис': [
    { id: 'why',     label: 'Зачем это вообще нужно' },
    { id: 'lincom',  label: 'Линейная комбинация и оболочка' },
    { id: 'lindep',  label: 'Линейная зависимость и независимость' },
    { id: 'gauss',   label: 'Метод Гаусса' },
    { id: 'rank',    label: 'Ранг — число настоящих измерений' },
    { id: 'basis',   label: 'Базис — минимальный набор осей' },
    { id: 'example', label: 'Полная прогонка матрицы 3×4' },
    { id: 'four',    label: 'Четыре фундаментальных подпространства' },
    { id: 'props',   label: 'Ключевые свойства ранга' },
    { id: 'ds',      label: 'Ранг и базис в Data Science' },
    { id: 'check',   label: 'Проверь себя' },
  ],
  'Собственные значения': [
    { id: 'motivation', label: 'Зачем это вообще нужно' },
    { id: 'geometry',   label: 'Что мы ищем' },
    { id: 'det',        label: 'Диагональная матрица — интуиция' },
    { id: 'char-eq',    label: 'Характеристическое уравнение' },
    { id: 'example2x2', label: 'Полная прогонка: матрица 2×2' },
    { id: 'properties', label: 'Ключевые свойства' },
    { id: 'complex',    label: 'Комплексные собственные значения' },
    { id: 'example3x3', label: 'Матрица 3×3 с кратным λ' },
    { id: 'diag',       label: 'Диагонализация: A = VΛV⁻¹' },
    { id: 'nodiag',     label: 'Когда диагонализовать нельзя' },
    { id: 'ds',         label: 'Где это работает в Data Science' },
  ],
  'Сингулярное разложение (SVD)': [
    { id: 'why',        label: 'Зачем это вообще нужно' },
    { id: 'geo',        label: 'Окружность → эллипс' },
    { id: 'algebra',    label: 'Алгебраический вход: AᵀA' },
    { id: 'definition', label: 'Формальное определение SVD' },
    { id: 'example',    label: 'Полное вычисление SVD 2×2' },
    { id: 'props',      label: 'Ключевые свойства' },
    { id: 'four',       label: 'SVD и четыре подпространства' },
    { id: 'links',      label: 'Связь с другими темами' },
    { id: 'ds',         label: 'SVD в Data Science' },
    { id: 'check',      label: 'Проверь себя' },
  ],
  'Сингулярное разложение (SVD) — часть 1': [
    { id: 'why',        label: 'Зачем это вообще нужно' },
    { id: 'geo',        label: 'Окружность → эллипс' },
    { id: 'algebra',    label: 'Алгебраический вход: AᵀA' },
    { id: 'definition', label: 'Формальное определение SVD' },
    { id: 'example',    label: 'Полное вычисление SVD 2×2' },
    { id: 'props',      label: 'Ключевые свойства' },
    { id: 'four',       label: 'SVD и четыре подпространства' },
    { id: 'links',      label: 'Связь с другими темами' },
    { id: 'ds',         label: 'SVD в Data Science' },
    { id: 'check',      label: 'Проверь себя' },
  ],
  'Сингулярное разложение (SVD) — часть 2': [
    { id: 'why',      label: 'Зачем это вообще нужно' },
    { id: 'low-rank', label: 'Низкоранговая аппроксимация' },
    { id: 'eckart',   label: 'Эккарт–Янг: почему это оптимально' },
    { id: 'image',    label: 'Сжатие изображения' },
    { id: 'choose',   label: 'Как выбрать k' },
    { id: 'pca',      label: 'SVD и PCA' },
    { id: 'recs',     label: 'Рекомендательные системы' },
    { id: 'pinv',     label: 'Псевдообращение и МНК' },
    { id: 'noise',    label: 'Шумоподавление' },
    { id: 'map',      label: 'SVD как швейцарский нож' },
    { id: 'check',    label: 'Проверь себя' },
  ],
  'Предел и непрерывность': [
    { id: 'lc-intro',         label: 'Фундамент ML' },
    { id: 'lc-theory',        label: 'Определения и теоремы' },
    { id: 'lc-anim',          label: 'ε-δ в действии' },
    { id: 'lc-proof',         label: 'Пошаговое доказательство' },
    { id: 'lc-discontinuity', label: 'Точки разрыва' },
    { id: 'lc-activations',   label: 'Функции активации' },
    { id: 'lc-optimization',  label: 'Градиентный спуск' },
    { id: 'lc-bigo',          label: 'Асимптотика Big O' },
  ],
  'Производная и градиент': [
    { id: 'dg-why',        label: 'Зачем это вообще нужно' },
    { id: 'dg-avgspeed',   label: 'От средней скорости к мгновенной' },
    { id: 'dg-definition', label: 'Определение производной' },
    { id: 'dg-geometry',   label: 'Геометрия: касательная' },
    { id: 'dg-rules',      label: 'Правила дифференцирования' },
    { id: 'dg-table',      label: 'Таблица производных' },
    { id: 'dg-monotone',   label: 'Знак f′: монотонность' },
    { id: 'dg-second',     label: 'Вторая производная' },
    { id: 'dg-diffcont',   label: 'Дифференцируемость и непрерывность' },
    { id: 'dg-gradient',   label: 'Частные производные и градиент' },
    { id: 'dg-ds',         label: 'Производная в Data Science' },
    { id: 'dg-check',      label: 'Проверь себя' },
  ],
  'Частные производные': [
    { id: 'pd-why',        label: 'Зачем это' },
    { id: 'pd-multivars',  label: 'Функции n переменных' },
    { id: 'pd-definition', label: 'Определение' },
    { id: 'pd-geometry',   label: 'Геометрия' },
    { id: 'pd-technique',  label: 'Техника вычисления' },
    { id: 'pd-gradient',   label: 'Градиент' },
    { id: 'pd-stationary', label: 'Стационарные точки' },
    { id: 'pd-saddle',     label: 'Седловые точки' },
    { id: 'pd-hessian',    label: 'Гессиан' },
    { id: 'pd-classify',   label: 'Классификация' },
    { id: 'pd-chain',      label: 'Цепное правило' },
    { id: 'pd-ds',         label: 'Data Science' },
    { id: 'pd-check',      label: 'Проверь себя' },
  ],
  'Градиентный спуск — часть 1': [
    { id: 'gd1-why',       label: 'Зачем это' },
    { id: 'gd1-metaphor',  label: 'Слепой альпинист' },
    { id: 'gd1-1d',        label: 'Одномерный спуск' },
    { id: 'gd1-lr',        label: 'Learning rate' },
    { id: 'gd1-2d',        label: 'Двумерный случай' },
    { id: 'gd1-ravine',    label: 'Овраги и κ' },
    { id: 'gd1-algorithm', label: 'Алгоритм Batch GD' },
    { id: 'gd1-example',   label: 'Маленький пример' },
    { id: 'gd1-links',     label: 'Связь с темами' },
    { id: 'gd1-check',     label: 'Проверь себя' },
  ],
  'Градиентный спуск — часть 2': [],
};
