import { useMemo, useState } from 'react';

type Matrix = number[][]; type Preset = 'cross' | 'chess' | 'noise';
const N = 12;
function dot(a:number[],b:number[]){return a.reduce((s,x,i)=>s+x*b[i],0);} function norm(v:number[]){const n=Math.hypot(...v)||1; return v.map(x=>x/n);} function matVec(A:Matrix,v:number[]){return A.map(r=>dot(r,v));} function transpose(A:Matrix){return A[0].map((_,j)=>A.map(r=>r[j]));} function mul(A:Matrix,B:Matrix){const BT=transpose(B); return A.map(r=>BT.map(c=>dot(r,c)));}
function image(p: Preset): Matrix { if(p==='cross') return Array.from({length:N},(_,r)=>Array.from({length:N},(_,c)=>r===5||r===6||c===5||c===6?235:35)); if(p==='chess') return Array.from({length:N},(_,r)=>Array.from({length:N},(_,c)=>(Math.floor(r/2)+Math.floor(c/2))%2?230:30)); let s=7; return Array.from({length:N},()=>Array.from({length:N},()=>{s=(s*1664525+1013904223)>>>0; return Math.round((s/2**32)*255);})); }
function svdApprox(A: Matrix, k: number) { const AT=transpose(A); let C=mul(AT,A); const terms:{sig:number;u:number[];v:number[]}[]=[]; for(let t=0;t<k;t++){ let v=norm(Array.from({length:N},(_,i)=>Math.sin((t+1)*(i+2)))); for(let it=0;it<80;it++) v=norm(matVec(C,v)); const Cv=matVec(C,v); const lam=Math.max(0,dot(v,Cv)); const sig=Math.sqrt(lam); if(sig<1e-6) break; const u=matVec(A,v).map(x=>x/sig); terms.push({sig,u,v}); C=C.map((row,r)=>row.map((x,c)=>x-lam*v[r]*v[c])); } const R=Array.from({length:N},()=>Array(N).fill(0)); for(const {sig,u,v} of terms) for(let r=0;r<N;r++) for(let c=0;c<N;c++) R[r][c]+=sig*u[r]*v[c]; return R; }
function PixelGrid({ data }: { data: Matrix }) { return <div className="grid w-72 grid-cols-12 overflow-hidden rounded-2xl border border-slate-200">{data.flatMap((row,r)=>row.map((v,c)=><div key={`${r}-${c}`} className="aspect-square transition-colors duration-300" style={{background:`rgb(${Math.max(0,Math.min(255,Math.round(v)))},${Math.max(0,Math.min(255,Math.round(v)))},${Math.max(0,Math.min(255,Math.round(v)))})`}}/>))}</div>; }
function tip(k:number){ if(k===12) return 'Ранг 12: полное изображение, 144 числа. Сжатие 0%.'; if(k>=6) return 'Ранг 6+: изображение узнаваемо, но детали сглажены. Сжатие около 75%.'; if(k>=2) return 'Ранг 2–5: видна основная структура — горизонтали, вертикали и крупные пятна.'; return 'Ранг 1: всё изображение — один повторяющийся паттерн. Максимальное сжатие.'; }
export default function LowRankApproximationLab(){ const [preset,setPreset]=useState<Preset>('cross'); const [rank,setRank]=useState(2); const [show,setShow]=useState(false); const A=useMemo(()=>image(preset),[preset]); const approx=useMemo(()=>svdApprox(A,rank),[A,rank]); const used=rank*rank; const compression=((144-used)/144)*100;
return <div><h4 className="text-xl font-extrabold text-slate-900">Лаборатория 5: «Ранг и сжатие»</h4><p className="mt-2 text-sm text-slate-700">Маленькое изображение — это матрица 12×12. Ранг управляет сложностью картинки и силой сжатия.</p>
  <div className="mt-4 flex flex-wrap gap-2">{(['cross','chess','noise'] as Preset[]).map(p=><button key={p} onClick={()=>setPreset(p)} className={`rounded-xl border px-3 py-2 text-sm font-bold ${preset===p?'border-indigo-500 bg-indigo-50 text-indigo-800':'border-slate-200 bg-white'}`}>{p==='cross'?'Крест':p==='chess'?'Шахматная доска':'Случайный шум'}</button>)}<label className="rounded-xl border px-3 py-2 text-sm"><input type="checkbox" checked={show} onChange={e=>setShow(e.target.checked)}/> Показать SVD</label></div>
  <div className="mt-5 rounded-2xl border border-slate-200 bg-slate-50 p-4"><div className="flex justify-between font-bold"><span>Ранг k</span><span>{rank}</span></div><input type="range" min={1} max={12} step={1} value={rank} onChange={e=>setRank(Number(e.target.value))} className="w-full accent-indigo-600"/></div>
  <div className="mt-5 grid gap-6 lg:grid-cols-[auto_auto_1fr]"><div><div className="mb-2 text-sm font-extrabold">Исходное 12×12</div><PixelGrid data={A}/></div><div><div className="mb-2 text-sm font-extrabold">Аппроксимация ранга {rank}</div><PixelGrid data={approx}/></div><div className="space-y-3"><div className="rounded-2xl border bg-white p-4"><div className="text-xs font-extrabold uppercase tracking-widest text-slate-500">Использовано</div><div className="text-4xl font-black text-indigo-700">{used}</div><p className="text-sm text-slate-600">чисел из 12×12=144</p><div className="mt-3 h-3 overflow-hidden rounded-full bg-slate-200"><div className="h-full bg-indigo-600" style={{width:`${Math.min(100,used/144*100)}%`}}/></div></div><div className="rounded-2xl border bg-white p-4"><div className="text-xs font-extrabold uppercase tracking-widest text-slate-500">Сжатие</div><div className="text-4xl font-black text-emerald-700">{compression.toFixed(0)}%</div><p className="mt-2 text-sm text-slate-700">{tip(rank)}</p></div></div></div>
  {show&&<div className="mt-5 rounded-2xl border border-violet-200 bg-violet-50 p-4 text-sm text-violet-900"><b>Мостик к SVD:</b> A≈UₖΣₖVₖᵀ. Мы оставляем k главных компонент; матрицы U, Σ и Vᵀ скрыты внутри вычисления аппроксимации.</div>}
  <div className="mt-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900"><b>💡 Ключевое наблюдение:</b> ранг изображения — это его «сложность». SVD-сжатие оставляет k главных компонент и даёт оптимальное приближение матрицей ранга k.</div>
</div>; }
